[build]
  publish = "_site"
  command = "npm run build"

# Plugins
[[plugins]]
  package = "netlify-plugin-11ty"
  [plugins.inputs]
    cache_img = './assets/img/build'

# Better blog urls
[[redirects]]
  from = "/:year/:month/:day/:slug"
  to = "/blog/:slug"
  status = 301

# Redirect some old subdomains
[[redirects]]
  from = "https://wpthemes.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "http://wpthemes.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "https://www.wpthemes.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "http://www.wpthemes.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "https://accessiblezen.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "http://accessiblezen.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "https://www.accessiblezen.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

[[redirects]]
  from = "http://www.accessiblezen.davidakennedy.com/*"
  to = "https://davidakennedy.com/projects/accessible-zen"
  status = 301
  force = true

# Redirect Netlify subdomain
[[redirects]]
  from = "https://davidakennedy.netlify.app/*"
  to = "https://davidakennedy.com"
  status = 301
  force = true

[[redirects]]
  from = "http://davidakennedy.netlify.app/*"
  to = "https://davidakennedy.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.davidakennedy.netlify.app/*"
  to = "https://davidakennedy.com"
  status = 301
  force = true

[[redirects]]
  from = "http://www.davidakennedy.netlify.app/*"
  to = "https://davidakennedy.com"
  status = 301
  force = true

[[redirects]]
  from = "/feed"
  to = "/feed/index.xml"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src=self,
      style-src=self; unsafe-inline,
      script-src=self; unsafe-inline,
      img-src=self
    '''
    Permissions-Policy = '''
      accelerometer=(none),
      ambient-light-sensor=(none),
      autoplay=(none),
      camera=(none),
      encrypted-media=(none),
      fullscreen=(none),
      geolocation=(none),
      gyroscope=(none),
      magnetometer=(none),
      microphone=(none),
      midi=(none),
      payment=(none),
      picture-in-picture=(none),
      speaker=(none),
      usb=(none),
      vibrate=(none),
      vr=(none)
    '''
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
